entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      middlewares:
      - SecHeaders@file
#      tls:
#        certResolver: myresolver

accessLog: {}

providers:
  docker:
    exposedByDefault: false

  file:
    directory: /etc/traefik/custom/
    watch: true

#certificatesResolvers:
#  myresolver:
#    acme:
#      email: "foo.bar@mydomain.com"
#      storage: "/letsencrypt/acme.json"
#      tlsChallenge: {}